booking:
  property: Booking profile dev

spring:
#conexion base de datos
    datasource:
    hikari:
      maximum-pool-size: 1
    driver-class-name: org.postgresql.Driver

#configuracion de jpa
    jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update

#patron de escritura del log
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:- [%p]} %m%n"