product:
  propertie: Produt profile dev

app:
  testProp: Property of test update

#patron de escritura del log
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:- [%p]} %m%n"